### ISSUE TITLE
Docker | actions.py can not link to another py file

### ISSUE THREAD

**Issue by lansedebing** [RasaHQ/rasa_core_sdk#54]
[root@localhost actions]# ls
actions.py  log.py
[root@localhost actions]# cd ..
[root@localhost multiplition]# docker run -v $(pwd)/actions:/app/actions rasa/rasa_core_sdk:latest run python -m rasa_core_sdk.endpoint --actions actions.actions
2019-02-23 10:02:24 INFO     __main__  - Starting action endpoint server...
2019-02-23 10:02:24 ERROR    rasa_core_sdk.executor  - Failed to register package 'actions.actions'.
Traceback (most recent call last):
  File "/app/rasa_core_sdk/executor.py", line 144, in register_package
    self._import_submodules(package)
  File "/app/rasa_core_sdk/executor.py", line 131, in _import_submodules
    package = importlib.import_module(package)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/actions/actions.py", line 3, in <module>
    from log import Log
ModuleNotFoundError: No module named 'log'

**Comment by akelad** [comment]
Please fill out the issue template and provide some more details

**Rasa Core version**:

**Python version**: 

**Operating system** (windows, osx, ...):

**Issue**:



**Content of domain file** (if used & relevant):
```yaml

```

**Comment by lansedebing** [comment]
i used **docker** to run on Centos 7.    resa_core_sdk is   **rasa/rasa_core_sdk:latest**

**Issue**:  My actions.py depends log.py.   Run without docker, everything was ok. But in docker, I got ModuleNotFoundError: No module named 'log'


**Command**:
docker run -v $(pwd)/actions:/app/actions rasa/rasa_core_sdk:latest run python -m rasa_core_sdk.endpoint --actions actions.actions

**Comment by akelad** [comment]
I assume you're using the pre-built docker image? That won't be aware of the log file, you'll need to include that in the docker image and also add an `__init__.py` to whichever directory you're loading from so it reads it as a python module. 
Let me know if that works
