### ISSUE TITLE
rasa_core_sdk.executor  - Failed to register package 'actions'.

### ISSUE THREAD

**Issue by HovHak** [RasaHQ/rasa_core_sdk#71]
**Rasa Core SDK version**:13.3

**Python version**: 3.6

**Operating system** (windows, osx, ...):Windows 10

**Issue**: I am trying to run actions server for my custom actions to perform interactive training but when i try to run it it shows this error 

C:\Users\ferar>python -m rasa_core_sdk.endpoint --actions actions
2019-04-24 05:35:38 INFO     __main__  - Starting action endpoint server...
2019-04-24 05:35:38 ERROR    rasa_core_sdk.executor  - Failed to register package 'actions'.
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\rasa_core_sdk\executor.py", line 144, in register_package
    self._import_submodules(package)
  File "C:\Python36\lib\site-packages\rasa_core_sdk\executor.py", line 131, in _import_submodules
    package = importlib.import_module(package)
  File "C:\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'actions'
2019-04-24 05:35:38 INFO     __main__  - Action endpoint is up and running. on ('0.0.0.0', 5055)

it is running essentially but it has failed to register package 'actions'

**Content of domain file** (if used & relevant):
```yaml

```

**Comment by nehavbishnoi** [comment]
why am i getting this msg?
 rasa_sdk.executor  - Failed to register package 'actions'

how can i rectify this?
